# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.
---
name: egeria-base
description: A Helm chart for Egeria simple platform deployment
apiVersion: v2
version: 4.3.0
appVersion: "4.3"
icon: https://raw.githubusercontent.com/odpi/egeria/99016e77167fa30dcfade809b061358a92a59973/assets/img/egeria.png
keywords:
  - odpi, egeria, base, simple
sources:
  - https://github.com/odpi/egeria
home: https://github.com/odpi/egeria
maintainers:
  - name: Nigel Jones
    email: nigel.l.jones+git@gmail.com
dependencies:
  - name: strimzi-kafka-operator
    version: 0.35.1
    repository: https://strimzi.io/charts/
    condition: strimzi.enabled
  # TODO - reinstate dependencies after initial publish
  #- name: egeria-lineage
  #  version: 4.0.0
  #  repository: https://odpi.github.io/egeria-charts
  #  condition: egeria-lineage.enabled
