# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.
---
name: egeria-base
description: Egeria simple deployment (platform, react UI)
apiVersion: v2
version: 3.7.0-prerelease.1
appVersion: 3.7
icon: https://raw.githubusercontent.com/odpi/egeria/99016e77167fa30dcfade809b061358a92a59973/assets/img/egeria.png
keywords:
  - odpi, egeria, base, simple
sources:
  - https://github.com/odpi/egeria
home: https://github.com/odpi/egeria
maintainers:
  - name: Nigel Jones
    email: nigel.l.jones+git@gmail.com
dependencies:
  - name: strimzi-kafka-operator
    version: 0.28.0
    repository: https://strimzi.io/charts/
