# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.
---
name: odpi-egeria-lab
description: Egeria lab environment
apiVersion: v1
version: 3.3.0-prerelease.6
appVersion: 3.3-SNAPSHOT
icon: https://raw.githubusercontent.com/odpi/egeria/99016e77167fa30dcfade809b061358a92a59973/assets/img/egeria.png
keywords:
  - odpi, egeria, lab, jupyter, notebook
sources:
  - https://github.com/odpi/egeria
home: https://github.com/odpi/egeria
maintainers:
  - name: Christopher Grote
    email: chris@thegrotes.net
  - name: Nigel Jones
    email: nigel.l.jones+git@gmail.com
dependencies:
  - name: kafka
    version: 14.2.2
    repository: https://charts.bitnami.com/bitnami
