# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.
---
name: egeria-cts
description: Egeria Conformance Test Suite deployment to Kubernetes
apiVersion: v2
version: 3.10.0-prerelease.1
appVersion: "3.10"
icon: https://raw.githubusercontent.com/odpi/egeria/99016e77167fa30dcfade809b061358a92a59973/assets/img/egeria.png
keywords:
  - odpi, egeria, cts
sources:
  - https://github.com/odpi/egeria
home: https://github.com/odpi/egeria
maintainers:
  - name: Christopher Grote
    email: chris@thegrotes.net
  - name: Nigel Jones
    email: nigel.l.jones+git@gmail.com
dependencies:
  - name: strimzi-kafka-operator
    version: 0.29.0
    repository: https://strimzi.io/charts/
    condition: strimzi.enabled


