# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-env
  labels:
    app.kubernetes.io/name: {{ include "egeria-base.name" . }}
    helm.sh/chart: {{ include "egeria-base.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  # Disables strict checking by egeria of TLS certs. Needed for self-signed
  STRICT_SSL: "false"
  {{- if .Values.egeria.logging }}
  # Not set in values -- Only expected to be used for debugging. For regular use Audit Logs should be sufficient
  LOGGING_LEVEL_ROOT: {{ .Values.egeria.logging }}
  {{- end }}
  EGERIA_ENDPOINT: https://{{ .Release.Name }}-platform:9443
  EGERIA_USER: {{ .Values.global.egeria.user }}
  EGERIA_COHORT: {{ .Values.egeria.cohort }}
  KAFKA_ENDPOINT: {{ include "egeria-base.KafkaClusterEndpoint" .}}
  {{- if .Values.global.kafka.consumerGroupID }}
  KAFKA_CONSUMER_GROUP_ID: {{ .Values.global.kafka.consumerGroupID }}
  {{- end }}
  EGERIA_SERVER: {{ .Values.global.egeria.serverName }}
  VIEW_SERVER: {{ .Values.egeria.viewServerName }}
  EGERIA_PRESENTATIONSERVER_SERVER_{{ .Values.egeria.viewOrg }}: "{\"remoteServerName\":\"{{ .Values.egeria.viewServerName }}\",\"remoteURL\":\"https://{{ .Release.Name }}-platform:9443\"}"
  EGERIA_PRESENTATIONSERVER_REJECTUNAUTHORIZED_FOR_OMAG: "false"
  BASE_TOPIC_NAME: {{ .Values.egeria.baseTopicName }}
  # Server autostart
  {{- if (index .Values "egeria-lineage" "enabled") }}
  POSTCONFIG_STARTUP_SERVER_LIST: {{ .Values.global.egeria.serverName }},{{ .Values.egeria.viewServerName }},{{ .Values.lineage.serverName }}
  {{- else }}
  POSTCONFIG_STARTUP_SERVER_LIST: {{ .Values.global.egeria.serverName }},{{ .Values.egeria.viewServerName }}
  {{- end }}
  STARTUP_CONFIGMAP: {{ .Release.Name }}-autostart
  LOADER_PATH: /extlib,/deployments/server/extralib,/deployments/server/lib
  # Additional values inserted by user
{{- with .Values.extraEnv }}
{{ tpl . $ | indent 2 }}
{{- end }}
