# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-env
  labels:
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    helm.sh/chart: {{ include "myapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  # Disables strict checking by egeria of TLS certs. Needed for self-signed
  STRICT_SSL: "false"
  # Not set in values -- Only expected to be used for debugging. For regular use Audit Logs should be sufficient
  {{ if .Values.egeria.logging }}
  LOGGING_LEVEL_ROOT: {{ .Values.egeria.logging }}
  {{ end }}
  EGERIA_ENDPOINT: https://{{ .Release.Name }}-platform:9443
  EGERIA_USER: {{ .Values.egeria.user }}
  EGERIA_COHORT: {{ .Values.egeria.cohort }}
  KAFKA_ENDPOINT: {{ .Release.Name }}-strimzi-kafka-bootstrap:9092
  EGERIA_SERVER: {{ .Values.egeria.serverName }}
  VIEW_SERVER: {{ .Values.egeria.viewServerName }}
  EGERIA_PRESENTATIONSERVER_SERVER_{{ .Values.egeria.viewOrg }}: "{\"remoteServerName\":\"{{ .Values.egeria.viewServerName }}\",\"remoteURL\":\"https://{{ .Release.Name }}-platform:9443\"}"
  EGERIA_PRESENTATIONSERVER_REJECTUNAUTHORIZED_FOR_OMAG: "false"
  # Server autostart
  POSTCONFIG_STARTUP_SERVER_LIST: {{ .Values.egeria.serverName }},{{ .Values.egeria.viewServerName }}
  STARTUP_CONFIGMAP: {{ .Release.Name }}-autostart
  LOADER_PATH: /extlib,/deployments/server/lib
  # Additional values inserted by user
{{- with .Values.extraEnv }}
{{ tpl . $ | indent 2 }}
{{- end }}
